import React from "react";
import Image from "next/image";
import requests from "../../utils/requests";
import Head from "next/head";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import Router from "next/dist/server/router";
import { useRouter } from "next/dist/client/router";

const details = ({ movie }) => {
   const router = useRouter();
   const BASE_URL = "https://image.tmdb.org/t/p/original/";
   return (
      <>
         <Head>
            <title>Hulu</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
               rel="preconnect"
               href="https://fonts.gstatic.com"
               crossorigin
            />
            <link
               href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap"
               rel="stylesheet"
            />
         </Head>

         <div className="relative h-screen items-center">
            <ArrowLeftIcon
               className="absolute left-10 top-10 z-30 h-7 text-white cursor-pointer"
               onClick={() => router.back()}
            />
            <div className="flex items-center fixed h-full w-full z-10 sm:bg-gradient-to-r sm:from-[#06202A]">
               <div className="container mx-10">
                  <h1 className="text-4xl tracking-tight font-extrabold text-white sm:text-5xl md:text-5xl sm:whitespace-nowrap">
                     <span className="block xl:inline">
                        {movie.original_title}
                     </span>
                  </h1>
                  <p className="mt-3 text-base font-light text-white sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-sm lg:mx-0">
                     {movie.overview}
                  </p>
                  <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                     <div className="rounded-md shadow">
                        <a
                           href="#"
                           className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-green-600 hover:bg-green-700 md:py-4 md:text-lg md:px-10"
                        >
                           Watch Now
                        </a>
                     </div>
                     <div className="mt-3 sm:mt-0 sm:ml-3">
                        <a
                           href="#"
                           className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-green-700 bg-white hover:bg-green-200 md:py-4 md:text-lg md:px-10"
                        >
                           Watch Trailer
                        </a>
                     </div>
                  </div>
               </div>
            </div>

            <div className="opacity-10 sm:opacity-70">
               <Image
                  src={
                     `${BASE_URL}${movie.backdrop_path || movie.poster_path}` ||
                     `${BASE_URL}${movie.backdrop_path}`
                  }
                  className="object-cover object-top"
                  layout="fill"
                  //   height={1080}
                  //   width={1920}
               />
            </div>
         </div>
      </>
   );
};

export default details;

export async function getServerSideProps(context) {
   const id = context.params.details;

   const request = await fetch(
      `https://api.themoviedb.org/3/movie/${
         id + requests.fetchMovieDetails.url
      }`
   ).then((res) => res.json());

   return {
      props: {
         movie: request,
      },
   };
}
