import React, { useEffect, useState } from "react";
import requests from "../utils/requests";
import Nav from "../components/Nav";
import { SearchIcon } from "@heroicons/react/outline";
import Head from "next/head";
import Header from "../components/Header";
import Thumbnail from "../components/Thumbnail";

const search = () => {
    const [query, setQuery] = useState("");
    const [queryMsg, setQueryMsg] = useState("");
    const [results, setResults] = useState([]);

    const getSearchResults = async () => {
        const request = await fetch(`
    https://api.themoviedb.org/3${requests.fetchSearchResults.url}&query=${query}`)
            .then((res) => res.json())
            .then((res) => {
                console.log("Received ", res);
                setResults(res.results);
                setQueryMsg(query && `Search results for "${query}"`);
            })
            .catch((err) => console.log(err));
    };

    useEffect(() => {
        getSearchResults();
    }, [query]);

    return (
        <>
            <Head>
                <title>Hulu</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Header />
            <div className="flex items-start mx-20">
                <div className="pt-2 w-96 text-start relative text-gray-600">
                    <input
                        className="bg-white h-10 w-96 px-5 pr-16 rounded-lg text-sm border-2 focus:border-green-600 focus:outline-none"
                        type="text"
                        name="search"
                        placeholder="Movie/TV Show name goes here"
                        onChange={(event) => setQuery(event.target.value)}
                    />
                    <button
                        type="submit"
                        className="absolute right-0 top-0 mt-5 mr-4"
                    >
                        <SearchIcon className="h-4 text-[#06202A]" />
                    </button>
                </div>
            </div>
            <h1 className="text-3xl mx-20 mt-14">{queryMsg}</h1>
            <div className="px-5 my-10 sm:grid md:grid-cols-2 xl:grid-cols-3 3xl:flex flex-wrap justify-center">
                {results?.map((result) => (
                    <Thumbnail key={result.id} result={result} />
                ))}
            </div>
        </>
    );
};

export default search;
